[project]
name = "incels-wiki-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "auto-archiver>=1.1.6",
    "scrapy>=2.13.2",
]
